# Generated by Django 2.2.10 on 2020-04-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=228, null=True)),
                ('img_url', models.CharField(blank=True, max_length=228, null=True)),
                ('title', models.CharField(blank=True, max_length=228, null=True)),
                ('content', models.CharField(blank=True, max_length=228, null=True)),
            ],
            options={
                'verbose_name': 'test表',
                'db_table': 'test',
            },
        ),
    ]
